/**
 * 시트 기준 병원명 다국어 매핑 (KR → en/th/hi/tl/ar/ru, zh_TW, ja_JP)
 * - en: en_US, th_TH, hi_IN, tl_PH, ar_SA, ru_RU 에 동일 적용
 * - zh: zh_TW (중국어 번체)
 * - ja: ja_JP (일본어)
 */
export interface HospitalNameRow {
  kr: string;
  en: string;
  zh: string;
  ja: string;
}

export const HOSPITAL_NAME_MAPPING: HospitalNameRow[] = [
  { kr: '압구정미라클의원', en: 'Apgujeong Miracle Clinic', zh: 'Apgujeong Miracle Clinic', ja: '狎鴎亭ミラクル医院' },
  { kr: '스마일러치과의원', en: 'Smiler Dental', zh: 'Smiler Dental', ja: 'Smiler Dental' },
  { kr: '청담비포앤애프터클리닉', en: 'Cheongdam Before & After Clinic', zh: 'Cheongdam Before & After Clinic', ja: 'Cheongdam Before & After Clinic' },
  { kr: '닥터송포유의원', en: 'Dr.Song 4u Plastic Surgery', zh: 'Dr.Song 4u Plastic Surgery', ja: 'Dr.Song 4u Plastic Surgery' },
  { kr: '봉봉성형외과의원', en: 'BongBong Plastic Surgery', zh: 'BongBong Plastic Surgery', ja: 'BongBong Plastic Surgery' },
  { kr: 'V&MJ피부과의원', en: 'V&MJ Dermatology Clinic', zh: 'V&MJ Dermatology Clinic', ja: 'V&MJ Dermatology Clinic' },
  { kr: '연세다인성형외과의원', en: 'YONSEI DAIN Plastic Surgery', zh: 'YONSEI DAIN Plastic Surgery', ja: 'YONSEI DAIN Plastic Surgery' },
  { kr: '허쉬성형외과의원', en: 'HERSHE Plastic Surgery', zh: 'HERSHE Plastic Surgery', ja: 'HERSHE整形外科' },
  { kr: '플랜에스의원', en: 'PlanS Clinic', zh: 'PlanS Clinic', ja: 'プランエスクリニック' },
  { kr: '1%일퍼센트성형외과의원', en: '1% One Percent Plastic Surgery Clinic', zh: '1% One Percent Plastic Surgery Clinic', ja: '1パーセント整形外科' },
  { kr: '슈가성형외과의원', en: 'SUGAR Plastic Surgery', zh: 'SUGAR Plastic Surgery', ja: 'シュガー美容外科' },
  { kr: '피그마리온의원', en: 'Pygmalion Clinic', zh: 'Pygmalion Clinic', ja: 'Pygmalion Clinic' },
  { kr: '마인드성형외과의원', en: 'Mind Plastic Surgery', zh: 'Mind Plastic Surgery', ja: 'Mind Plastic Surgery' },
  { kr: '클래스원의원', en: 'CLASS ONE Clinic', zh: 'CLASS ONE Clinic', ja: 'CLASS ONE Clinic' },
  { kr: '247클리닉', en: '247 Clinic', zh: '247 Clinic', ja: '247 Clinic' },
  { kr: '디캐럿의원', en: 'DICARAT Clinic', zh: 'DICARAT Clinic', ja: 'DICARAT Clinic' },
  { kr: '제로원성형외과의원', en: 'ZERO ONE Plastic Surgery', zh: 'ZERO ONE Plastic Surgery', ja: 'ゼロワン美容整形外科' },
  { kr: 'RU성형외과의원', en: 'RU Plastic Surgery', zh: 'RU Plastic Surgery', ja: 'RU Plastic Surgery' },
  { kr: '에이블룸성형외과의원', en: 'ABLOOM Clinic', zh: 'ABLOOM Clinic', ja: 'ABLOOM Clinic' },
  { kr: '셀린의원 강남역', en: 'Celine Clinic Gangnam', zh: 'Celine Clinic Gangnam', ja: 'セリン議員江南駅' },
  { kr: '르에이치의원', en: 'LeH Clinic', zh: 'LeH Clinic', ja: 'LeH Clinic' },
  { kr: '다미의원', en: 'Dami Clinic', zh: 'Dami Clinic', ja: 'ダミクリニック' },
  { kr: '이즈의원', en: 'IZ Clinic', zh: 'IZ Clinic', ja: 'IZ Clinic' },
  { kr: '서울페이스21치과병원', en: 'SeoulFace21 Dental', zh: 'SeoulFace21 Dental', ja: 'ソウルフェイス21' },
  { kr: '미니쉬치과병원', en: 'Minish Dental Hospital', zh: 'Minish Dental Hospital', ja: 'Minish Dental Hospital' },
  { kr: '지우개의원', en: 'Eraser Clinic', zh: 'Eraser Clinic', ja: 'Eraser Clinic' },
  { kr: '멜론성형외과의원', en: 'Melon Plastic Surgery', zh: 'Melon Plastic Surgery', ja: 'メロン整形外科医院' },
  { kr: '모앤라인성형외과의원', en: 'Mo&Line Plastic Surgery', zh: 'Mo&Line Plastic Surgery', ja: '毛＆ライン美容形成外科' },
  { kr: '아이루미성형외과의원', en: 'iLUMI Plastic Surgery', zh: 'iLUMI Plastic Surgery', ja: 'iLUMI Plastic Surgery' },
  { kr: '스노우의원', en: 'Snow Aesthetic Surgery', zh: 'Snow Aesthetic Surgery', ja: 'スノウ医院' },
  { kr: '셀이즈의원', en: 'Cellis Clinic', zh: 'Cellis Clinic', ja: 'Cellis Clinic' },
  { kr: '청담쥬넥스의원', en: 'Jeunex Clinic', zh: 'Jeunex Clinic', ja: 'Jeunex Clinic' },
  { kr: '원셀의원', en: 'One Cell Clinic', zh: 'One Cell Clinic', ja: 'One Cell Clinic' },
  { kr: '디에이성형외과의원', en: 'DA Plastic Surgery', zh: 'DA Plastic Surgery', ja: 'DA整形外科' },
  { kr: 'UBA성형외과의원', en: 'UBA Plastic Surgery', zh: 'UBA Plastic Surgery', ja: 'UBA Plastic Surgery' },
  { kr: 'G7클리닉', en: 'G7 Clinic', zh: 'G7 Clinic', ja: 'G7 Clinic' },
  { kr: '히트성형외과의원', en: 'HIT Plastic Surgery', zh: 'HIT Plastic Surgery', ja: 'ヒート美容外科医院' },
  { kr: '허준원M.D.피부과의원', en: 'Huh Joon Won M.D. Dermatology Clinic', zh: 'Huh Joon Won M.D. Dermatology Clinic', ja: 'Huh Joon Won M.D. Dermatology Clinic' },
  { kr: '프라이빗성형외과의원', en: 'Private Plastic Surgery', zh: 'Private Plastic Surgery', ja: 'プライベート整形外科医院' },
  { kr: '팝성형외과의원', en: 'POP Plastic Surgery', zh: 'POP整形外科', ja: 'POP Plastic Surgery' },
  { kr: '티에스성형외과의원', en: 'TS Plastic Surgery', zh: 'TS整形外科', ja: 'TS美容外科' },
  { kr: '티알 트리니티 라파엘로 청담의원', en: 'TR Clinic', zh: 'TR Clinic', ja: 'TR Clinic' },
  { kr: '타코성형외과의원', en: 'TAKO Plastic Surgery', zh: 'TAKO Plastic Surgery', ja: 'TAKO美容外科協力病院' },
  { kr: '초이스라인의원', en: 'Choice line Clinic', zh: 'Choice line Clinic', ja: 'Choice line Clinic' },
  { kr: '청담서클의원', en: 'Cheongdam Circle Clinic', zh: 'Cheongdam Circle Clinic', ja: 'Cheongdam Circle Clinic' },
  { kr: '첫단추의원', en: 'First Button Clinic', zh: 'First Button Clinic', ja: 'First Button Clinic' },
  { kr: '처음처럼성형외과의원', en: 'Like The First Time Plastic Surgery', zh: 'Like The First Time Plastic Surgery', ja: 'チョクムチョクム 美容外科' },
  { kr: '제이티성형외과의원', en: 'JT Plastic Surgery', zh: 'JT 整形外科', ja: 'JT Plastic Surgery' },
  { kr: '자연주의성형외과의원', en: 'Natural Face Plastic Surgery', zh: '自然主義整形外科', ja: 'Natural Face Plastic Surgery' },
  { kr: '일미리성형외과의원', en: '1mm Plastic Surgery', zh: '1mm Plastic Surgery', ja: '1mm Plastic Surgery' },
  { kr: '이유구강악안면외과치과의원', en: 'EU Oral & Maxillofacial Surgery', zh: 'EU Oral & Maxillofacial Surgery', ja: 'EU口腔顎顔面外科' },
  { kr: '위버스성형외과의원', en: 'UVERSE Plastic Surgery', zh: 'UVERSE Plastic Surgery', ja: 'ウィバース美容整形外科医院' },
  { kr: '우리성형외과의원', en: 'Woori Plastic Surgery', zh: '友利整形外科', ja: 'WOORI美容外科' },
  { kr: '옥건헤어라인의원', en: 'Ok Hairline Clinic', zh: 'Ok Hairline Clinic', ja: 'Ok Hairline Clinic' },
  { kr: '오페라성형외과의원', en: 'OPERA Plastic Surgery', zh: 'OPERA Plastic Surgery', ja: 'オペラ整形外科' },
  { kr: '오케이성형외과', en: 'OK Plastic Surgery', zh: 'OK Plastic Surgery', ja: 'OK整形外科' },
  { kr: '옐로우성형외과의원', en: 'Yellow Plastic Surgery', zh: 'Yellow Plastic Surgery', ja: 'イエロー美容整形外科' },
  { kr: '연세YB의원', en: 'Yonsei YB Clinic', zh: 'Yonsei YB Clinic', ja: 'Yonsei YB Clinic' },
  { kr: '엠레드의원', en: 'AMRED Clinic', zh: 'AMRED Clinic', ja: 'エムレッドクリニック' },
  { kr: '엠디외과의원', en: 'MD Clinic', zh: 'MD外科', ja: 'MD Clinic' },
  { kr: '에이트성형외과의원', en: 'Eight Plastic Surgery Clinic', zh: 'Eight Plastic Surgery Clinic', ja: 'エイト美容外科医院' },
  { kr: '에이탑성형외과의원', en: 'ATOP Plastic Surgery', zh: 'ATOP Plastic Surgery', ja: 'ATOP Plastic Surgery' },
  { kr: '에이비성형외과의원', en: 'AB Plastic Surgery', zh: 'AB整形外科', ja: 'AB美容外科' },
  { kr: '아이팅성형외과의원', en: 'Eyeting Plastic Surgery', zh: 'Eyeting Plastic Surgery', ja: 'アイティン美容整形外科・皮膚科' },
  { kr: '아이큐성형외과의원', en: 'IQ Plastic Surgery', zh: 'IQ Plastic Surgery', ja: 'IQ Plastic Surgery' },
  { kr: '아이디병원', en: 'ID Hospital', zh: 'ID Hospital', ja: 'ID美容外科' },
  { kr: '셀리크의원', en: 'CELLIQUE Clinic', zh: 'CELLIQUE Clinic', ja: 'CELLIQUE Clinic' },
  { kr: '서진성형외과의원', en: 'Seojin Plastic Surgery', zh: 'Seojin Plastic Surgery', ja: 'ソジン美容整形外科' },
  { kr: '서울아이성형외과의원', en: 'Seoul i Plastic Surgery', zh: 'Seoul i Plastic Surgery', ja: 'Seoul i Plastic Surgery' },
  { kr: '새김성형외과의원', en: 'Saekim Plastic Surgery', zh: 'Saekim Plastic Surgery', ja: 'セギム整形外科' },
  { kr: '뽐나게빼의원', en: 'Bbae Clinic', zh: 'BBAE吸脂醫院', ja: 'ポムナゲ・ペー医院' },
  { kr: '브라운성형외과의원', en: 'BRAUN Plastic Surgery', zh: 'BRAUN Plastic Surgery', ja: 'ブラウン整形外科' },
  { kr: '뷰성형외과의원', en: 'View Plastic Surgery', zh: 'View Plastic Surgery', ja: 'ビュー美容外科' },
  { kr: '본디성형외과의원', en: 'BORN DI Plastic Surgery', zh: 'BORN DI Plastic Surgery', ja: 'BORN DI Plastic Surgery' },
  { kr: '밴셀의원', en: 'Vencell Clinic', zh: 'Vencell Clinic', ja: 'Vencell Clinic' },
  { kr: '미호성형외과의원', en: 'MIHO Plastic Surgery', zh: '美好整形外科', ja: 'MIHO Plastic Surgery' },
  { kr: '물방울성형외과의원', en: 'Stilla Plastic Surgery', zh: 'Stilla Plastic Surgery', ja: 'Stilla Plastic Surgery' },
  { kr: '문의원', en: 'Moon Clinic', zh: 'Moon Clinic', ja: 'Moon Clinic' },
  { kr: '모플러스성형외과의원', en: 'Moplus Plastic Surgery', zh: 'Moplus 整形医院', ja: 'Moplus Plastic Surgery' },
  { kr: '모즈의원', en: 'Mods Clinic', zh: '摩兹抗衰老中心', ja: 'モズクリニック' },
  { kr: '모제림성형외과의원', en: 'Mojelim Hair Transplant', zh: 'Mojelim Hair Transplant', ja: 'モジェリム植毛' },
  { kr: '모우림의원', en: 'Mowoolim Hair Clinic', zh: 'Mowoolim Hair Clinic', ja: 'Mowoolim Hair Clinic' },
  { kr: '모앤블레스의원', en: 'MO&BLESS Clinic', zh: 'MO&BLESS Clinic', ja: 'MO&BLESS Clinic' },
  { kr: '모디헤어플란트의원', en: 'Modi Hair Plant', zh: 'Modi Hair Plant', ja: 'Modi Hair Plant' },
  { kr: '모든모의원', en: 'Modeunmo Clinic', zh: '全毛医院', ja: 'Modeunmo Clinic' },
  { kr: '마블성형외과의원', en: 'Marble Plastic Surgery', zh: 'Marble Plastic Surgery', ja: 'Marble Plastic Surgery' },
  { kr: '리팅성형외과의원', en: 'Liting Plastic Surgery', zh: 'Liting Plastic Surgery', ja: 'リティング美容外科' },
  { kr: '리뉴얼의원', en: 'The Renewall Clinic', zh: 'The Renewall Clinic', ja: 'The Renewall Clinic' },
  { kr: '르메디크의원', en: 'Lmedique Clinic', zh: 'Lmedique Clinic', ja: 'Lmedique Clinic' },
  { kr: '루비성형외과의원', en: 'Ruby Plastic Surgery', zh: '如妃整形外科', ja: 'ルビー整形外科' },
  { kr: '로이셀의원', en: 'Roycel Clinic', zh: 'Roycel Clinic', ja: 'Roycel Clinic' },
  { kr: '레아트성형외과의원', en: 'Lesarts Plastic Surgery', zh: 'Lesarts Plastic Surgery', ja: 'レアート整形外科' },
  { kr: '레스트의원', en: 'Rest Clinic', zh: 'Rest Clinic', ja: 'Rest Clinic' },
  { kr: '레디성형외과의원', en: 'Ready Plastic Surgery', zh: 'Ready整形醫院', ja: 'レディ美容外科' },
  { kr: '라비앙성형외과의원', en: 'Lavian Plastic Surgery', zh: '拉菲安整形外科', ja: 'Lavian Plastic Surgery' },
  { kr: '데이뷰의원 강남점', en: 'DayBeau Clinic Gangnam', zh: 'DayBeau Clinic Gangnam', ja: 'DayBeau Clinic Gangnam' },
  { kr: '더새로이의원', en: 'The Seroi Clinic', zh: 'The Seroi Clinic', ja: 'The Seroi Clinic' },
  { kr: '더도어성형외과의원', en: 'The Door Plastic Surgery', zh: 'The Door Plastic Surgery', ja: 'The Door 整形外科' },
  { kr: '더난성형외과의원', en: 'The Nan Plastic Surgery', zh: 'The Nan Plastic Surgery', ja: 'The Nan Plastic Surgery' },
  { kr: '노트성형외과의원', en: 'Note Plastic Surgery', zh: 'Note整形外科', ja: 'ノート美容外科' },
  { kr: '노상훈성형외과의원', en: 'RohSangHoon Plastic Surgery', zh: 'RohSangHoon Plastic Surgery', ja: 'RohSangHoon Plastic Surgery' },
  { kr: '나나성형외과의원', en: 'NANA Plastic Surgery', zh: 'NANA Plastic Surgery', ja: 'NANA美容外科' },
  { kr: '기린성형외과의원', en: 'Girin Plastic Surgery', zh: 'Girin Plastic Surgery', ja: 'ギリン美容外科' },
  { kr: '강남로미모의원', en: 'Romimo Clinic', zh: 'Romimo Clinic', ja: '江南ロミモ医院' },
  { kr: '강남 리슬림의원', en: 'Gangnam Reslim Clinic', zh: 'Gangnam Reslim Clinic', ja: '江南リスリム医院' },
];
